apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,configurations/**/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,demo/argo-hub.yaml,demo/default.yaml,demo/demo-dev-rollout-reporter.yaml,demo/demo-dev-rollouts.yaml,demo/demo-qa-rollout-reporter.yaml,demo/demo-qa-rollouts.yaml,demo/demo-staging-rollout-reporter.yaml,demo/demo-staging-rollouts.yaml,demo/demo.yaml,demo/devops-demo.yaml,demo/prod-asia-rollout-reporter.yaml,demo/prod-asia-rollouts.yaml,demo/prod-east-rollout-reporter.yaml,demo/prod-east-rollouts.yaml,demo/prod-eu-rollout-reporter.yaml,demo/prod-eu-rollouts.yaml,demo/prod-west-rollout-reporter.yaml,demo/prod-west-rollouts.yaml,runtimes/demo/**/*.yaml,runtimes/demo/*.yaml}
      recurse: true
    path: resources
    repoURL: >-
      https://github.com/aperture-sci/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
