apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: accounts
spec:
  promotionFlows:
    - name: sequential-accounts
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[promotion:sequential-accounts]'
  promotionTemplateRef: promotion-config-accounts
