apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: cf-101
spec:
  promotionTemplate:
    versionSource:
      file: version.yaml
      jsonPath: $.version
    promotion:
      version.yaml:
        jsonPaths:
          - $.version
