apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: cf-101
spec:
  promotionFlows:
    - name: cf-101-flow
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '*promote*'
  promotionTemplate:
    versionSource:
      file: version.yaml
      jsonPath: $.version
    promotion:
      values.yaml:
        jsonPaths:
          - $.*.image
      version.yaml:
        jsonPaths:
          - $.version
