apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: color
spec:

  promotionTemplate:
    versionSource:
      file: kustomization.yaml
      jsonPath: $.images[?(@.name == "docker.io/aperturesci/rollouts-demo")].newTag
    promotion:
      kustomization.yaml:
        jsonPaths:
        - $.images[0].newTag
