apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: color
spec:

  promotionTemplate:
    versionSource:
      file: rollout.yaml
      jsonPath: $.spec.template.spec.containers[0].image
    promotion:
      rollout.yaml:
        jsonPaths:
        - $.spec.template.spec.containers[0].image
