apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: color
spec:

  promotionTemplate:
    versionSource:
      file: kustomization.yaml
      jsonPath: $.images[0].newTag
    promotion:
      kustomization.yaml:
        jsonPaths:
        - $.images[0].newTag
