apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: interest
spec:
  promotionFlows:
    - name: sequential-interest  
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      Chart.yaml:
        jsonPaths:
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.loans.image.tag
