apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: interest
spec:
  promotionFlows:
    - name: sequential-interest
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[willneverhappens]'
    - name: simple-pr-flow
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '*pr-flow*'
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      Chart.yaml:
        jsonPaths:
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.loans.image.tag
