apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: interest
spec:
  # promotionFlows:
  #   - name: sequential-interest
  #     gitTriggerSelectors:
  #       - key: commitMessage
  #         operator: In
  #         values:
  #           - '[willneverhappens]'
  #           # to be sure we can promote by hand
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      Chart.yaml:
        jsonPaths:
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.loans.image.tag
