apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: loan
spec:
  promotionFlows:
    - name: sequential-loan
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[promotion-sequential-loan]'
            - '* [promotion-sequential-loan] *'
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      Chart.yaml:
        jsonPaths:
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.loans.image.tag
