apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: loan
spec:
  promotionFlows:
    - name: trio-flow
      gitTriggerSelectors:
        - key: gitRevision
          operator: In
          values:
            - promotion
            - promote
        - key: commitMessage
          operator: In
          values:
            - promotion
            - promote
    - name: trio-hotfix
      gitTriggerSelectors:
        - key: gitRevision
          operator: In
          values:
            - hotfix
  promotionTemplate:
    versionSource:
      file: version.yaml
      jsonPath: $.version
    promotion:
      chart.yaml:
        jsonPaths:
          - $
      '':
        jsonPaths: []
