apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: membership
spec:
  # promotionFlows:
  #   - name: membership-sequential
  #     gitTriggerSelectors:
  #       - key: commitMessage
  #         operator: In
  #         values:
  #           - '[promotion-sequential-membership]'

  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      Chart.yaml:
        jsonPaths:
        - $.appVersion
      values.yaml:
        jsonPaths:
        - $.loans.image.tag
