apiVersion: codefresh.io/v1beta2
kind: Product
metadata:
  name: trio
spec:
  promotionFlows:
    - name: trio-flow
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - promotion:trio-flow
            - '*promotion:trio-flow*'
    - name: trio-hotfix
      gitTriggerSelectors:
        - key: gitRevision
          operator: In
          values:
            - hotfix
    - name: pr-flow-jira
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '*pr-jira*'
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      version.yaml:
        jsonPaths:
          - $.version
      Chart.yaml:
        jsonPaths:
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.buslog.image.tag
          - $.ctrlr.image.tag
          - $.flask-ui.image.tag
  concurrency: queue
