apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: trio
spec:
  promotionFlows:
    - name: trio-flow
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - promotion:trio-flow
    - name: trio-hotfix
      gitTriggerSelectors:
        - key: gitRevision
          operator: In
          values:
            - hotfix
  promotionTemplate:
    versionSource:
      file: Chart.yaml
      jsonPath: $.appVersion
    promotion:
      version.yaml:
        jsonPaths:
          - $.version
      Chart.yaml:
        jsonPaths:
          - $.appVersion
      values.yaml:
        jsonPaths:
          - $.buslog.image.tag
          - $.ctrlr.image.tag
          - $.flask-ui.image.tag
