apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: membership
spec:
  policy:
    postAction: smoketests
  priority: -100
  selector:
    product:
      names:
        - membership
