apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: membership
spec:
  policy:
    preAction: smoketests
    postAction: smoketests
    action: commit
  priority: -100
  selector:
    product:
      names:
        - membership
