apiVersion: v2
appVersion: 1.0.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.13.4
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh
    version: 0.13.4

    # repository: oci://quay.io/codefresh/dev
    # version: 0.0.0-fix-revert-argocd-bump-98d4306
