gitops-runtime:
  app-proxy:
    image:
      repository: quay.io/codefresh/cap-app-proxy
      tag: 1.2841.0
      pullPolicy: IfNotPresent
  argo-cd:
    eventReporter:
      enabled: true
      version: v2
      replicas: 4
      image:
        tag: v2.8-2023.12.13-3973ffbbd
      env:
        - name: USE_GRPC
          value: 'false'
    server:
      replicas: 2
      resources:
        requests:
          cpu: '0.3'
          memory: 400Mi
  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          serviceAccountName: workflows-default
    useDefaultArtifactRepo: true
    useStaticCredentials: false
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret: {}
        secretKeySecret: {}
        bucket: aperturedevops
        endpoint: s3.amazonaws.com
        insecure: false
        region: us-east-1
        roleARN: arn:aws:iam::336151728602:role/codefresh_s3
    server:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::336151728602:role/argo-workflows-kubecon-dev
    workflow:
      serviceAccount:
        create: true
        name: workflows-default
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::336151728602:role/argo-workflows-kubecon-dev
  global:
    codefresh:
      accountId: 641dfab29939b208915c0d4e
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        enabled: false
      name: gitops
      isConfigurationRuntime: true
  installer:
    skipValidation: true
