gitops-runtime:
  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          serviceAccountName: workflows-default
    useDefaultArtifactRepo: true
    useStaticCredentials: false
    artifactRepository:
      archiveLogs: true
      s3:
          accessKeySecret: {}
          secretKeySecret: {}
          bucket: aperturedevops
          endpoint: s3.amazonaws.com
          insecure: false
          region: us-east-1
          roleARN: arn:aws:iam::336151728602:role/codefresh_s3
    server:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::336151728602:role/argo-workflows-kubecon-dev"
    workflow:
      serviceAccount:
        create: true
        name: workflows-default
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::336151728602:role/argo-workflows-kubecon-dev"          

  global:
    codefresh:
      accountId: 641dfab29939b208915c0d4e
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        enabled: false
      name: gitops
  installer:
    skipValidation: true
