kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: docker-intg
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: docker-intg
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: docker-intg
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgDW3AywrCZXsJoPszkSnGBKlaQbFuCyKO4swNSFToec8WtgVp9aR6P8mWxOelaiyQ7wRALDJxmsDSUYaCKoHXpiuQa1ilpvMW8UmxdeOy5ht9Ycaj326xQ4CgNHg8Lgjszdhmm4C04KbW14LRReuPw09IKahU5CmBrl6yC0YmDGoG+e1smolJ4E1gYXhgJ1PavZPUR+bBjvCYFeTnboEjs/OWnBEMEWM59I3h1jn5Jn0xvGUW8/TZ63yPmdTpxPI9P76pGHreGOl4bQ+YndC1aC0Um/RdXbAYVEnG0mnjT2SfyhqWp5fRi1MFq2I27KIwfIWKQGEHskjHNIb6UJ2EtkPVX5+ONGF4kfAwaCWSPU6OSjpicwg1/sNQq3LKJXVddT5MsKws8ndmJcgC7WJCPzjXS9lIX3YlAkWhMEPTVujSJYTzkVrEas2REOfcScwyVTbCu3y0N1XvIYkSoGT0YAggXGtf0lD9O7j7oYDNEheEDoE3ZFlbT9yE6Ex1/nev8x+3zaQ1T6AMk0zq+rDsJ2cZoH011LmzBn/l3akdE9PJQ2yisHdUn5gOQpZ570XxxF3HoCb2LZVyoL5hAenHiP95N7x4mJckFf3GY99LrVhCUlW6RQ7w4PSQoUV/D9f2bxriADqr6sGvLXKgoSY4+3k+0HOuIRB2/MuLn5Y/4qKs2y9cDMYUTkrriyiibksLLSY/Owp5fED4+r2we3hXlTsQ==
