kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: jira-intg
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: jira-intg
    codefresh.io/integration-type: issue.jira
spec:
  template:
    metadata:
      name: jira-intg
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    api_token: >-
      AgBeDUsCdvxad+3tG8RqwlSiFuveaIEVr6GILrN7on3DImal/5rC5tnnXqg9F5bybZdMYTnQ2yYYVFqRGn1jE6G1s6wQivDc9sYDs2iUX2rsuiux7ReOZoaJPHTC4Dj5eA6dz7vuDvsHKza2ALyfNujsQ2WcNT9QwaidTUQRY8DSZVkY/uuK1D+l9vNWA1NlEA9r5DosjNdcBpnmOiQctf93BCUfH9addUZpQZWZGsF7VQS3rFw2/NHvPKJxXYpBrEf5T8Lx8JhblTP3/W/HqfuExoXwY8BdJwCm2XuRG21Rj6b8RWRJx4MGHQVBupx11QFxdTPBzme8HvCsfCB2gJnvWo4kF2FTZXF9KYU/2SKukx/e+9DZ7tFarZwHj2CVSE8xH3/N/gKYSEEdlqJ1tyjVIXP8Dchjx9iSlC5zf9OYs78XuayYrwivXbGOnfXpM3lzd9x3oW+wO/VE32QL0tAnlnzjppJLKTGJy05eDPJA8FNolQfC/vWfHGfG2rSCspKpuFhc+MVdG6R9q+rvlvI5zASdHrcWOWxsmUGlhTKTZ3NxQ+5Jf2oJrkKBt4GOnENHH27yejTwQGDHKIO/aksqO+8VQkemnTNxS4Hhv3tO5CqcWAofI+w3rJFmZNSGHTOJW0BC3xo+2ezEwm35lFH2bng70t2lCa9ccT6mTxl/AwfMf9FgQpgje1Xr1PPH+D7Q84HRph4vo574Xtw+9fRDI2JOY3HE4gKAuH7/FV3D3pvN3ZunSSdudiZV+t2u19wnJKfW3JmYPnc98UiJWWE5I1gafYvJOfw=
