apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: blog-test
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
        postAction: slack-notification
