apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: demo-app-view
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
