apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: demo1-flow
  annotations:
    description: this is a test
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
        postAction: test1
