apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: eti-test-new
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: staging
      dependsOn:
        - dev
      policy:
        action: commit
      hooks:
        onSuccess: post-action
