apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: eti-test
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
        preAction: eti-new
    - environment: staging
      dependsOn:
        - dev
      policy:
        action: commit
        preAction: eti-new
    - environment: prod-us
      dependsOn:
        - qa
        - staging
      policy:
        action: commit
        preAction: eti-new
