apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: eva-flow
  annotations:
    version: 0.0.2
    description: Flow to show Snow integration
spec:
  triggerEnvironment: dev
  promotionTimeoutLimit: 300
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
      hooks:
        onSuccess: service-now-close-success
        onFail: service-now-close-failure
  hooks:
    onStart: service-now-open
