apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: eva-flow
  annotations:
    version: 0.0.1
    description: Flow to show Snow integration
spec:
  triggerEnvironment: dev
  postTrigger: post-action
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        preAction: service-now-open
        postAction: service-now-close
        action: commit
    # - environment: staging
    #   dependsOn:
    #     - dev
    #   policy:
    #     preAction: pre-action
    #     postAction: post-action
    #     action: commit
    # - environment: production
    #   dependsOn:
    #     - staging
    #     - qa
    #   policy:
    #     preAction: pre-action
    #     postAction: post-action
    #     action: commit
