apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: eva-flow
  annotations:
    version: 0.0.1
    description: Flow to show Snow integration
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
  hooks:
    onStart: service-now-open
