apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name1: idan-test-flow
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: production
      dependsOn:
        - dev
      policy:
        action: commit
