apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: sprint-review
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: production
      dependsOn:
        - dev
