apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: termination-timout-test
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
    - environment: staging
      dependsOn:
        - qa
