apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: test
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: staging
      dependsOn:
        - dev
      policy:
        postAction: slack-notification
