apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: trio-flow
  annotations:
    version: 0.0.1
    description: Flow to show parallel deployment
spec:
  triggerEnvironment: dev
  postTrigger: post-action
  steps:
    - environment: staging
      dependsOn:
        - dev
      policy:
        preAction: pre-action
        postAction: post-action
        action: commit
    - environment: production
      dependsOn:
        - staging
        - early-adopters
      policy:
        preAction: pre-action
        postAction: post-action
        action: commit
    - environment: early-adopters
      dependsOn:
        - dev
