apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: trio-flow
  annotations:
    version: 0.0.1
    description: Flow to show parallel deployment
spec:
  triggerEnvironment: dev
  postTrigger: post-action
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        preAction: pre-action
        postAction: smoketests
        action: commit
    - environment: staging
      dependsOn:
        - qa
      policy:
        preAction: pre-action
        postAction: post-action
        action: commit
    - environment: prod-eu
      dependsOn:
        - staging
    - environment: prod-asia
      dependsOn:
        - staging
      policy:
        action: pr
    - environment: prod-us
      dependsOn:
        - prod-eu
        - prod-asia
      policy:
        action: pr
