# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)
# List of parameters available for Post Action Workflows. See full list of parameters in the documentation: https://codefresh.io/docs/gitops/promotions/promotion-hooks/#default-arguments-in-promotion-workflows-with-hooks

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: access-workflow-labels
  annotations:
    version: 0.0.1
    codefresh.io/workflow-origin: promotion
    description: Workflow to access the values in the Workflow labels
  labels:
    environment: production
spec:
  arguments:
    parameters:
      - name: APP_NAME
  serviceAccountName: cf-default-promotion-workflows-sa
  entrypoint: echo
  templates:
    - name: echo
      inputs:
        parameters:
          - name: environment-label
            value: "{{workflow.labels.environment}}"
      script:
        image: alpine
        command:
          - sh
        source: |
          echo "syncing {{workflow.parameters.APP_NAME}}"
          echo "something else"
          echo "{{workflow.labels.environment}}"
          echo "something else 2"
          echo "{{inputs.parameters.environment-label}}"
          