apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: post-action-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: post-action-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: post-action-role
subjects:
- kind: ServiceAccount
  name: post-action-sa
  namespace: demo

---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: post-action-sa
