apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pre-action-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pre-action-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pre-action-cr
subjects:
- kind: ServiceAccount
  name: pre-action-sa
  namespace: runtime

---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: pre-action-sa
