# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pre-action-hook
  annotations:
    codefresh.io/workflow-origin: promotion
    version: 0.0.1
    description: 'promotion workflow template'
spec:
  serviceAccountName: promotion-template
  arguments:
    parameters:
    - name: PRODUCT_NAME
  entrypoint: echo-pre-action-hook
  templates:
  - name: echo-pre-action-hook
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "syncing {{ workflow.parameters.PRODUCT_NAME }} "
