# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: service-now
  annotations:
    codefresh.io/workflow-origin: promotion
    version: 0.0.1
    description: 'promotion workflow template'
spec:
  serviceAccountName: promotion-template
  arguments:
    parameters:
    - name: APP_NAME
  entrypoint: snow-flow
  templates:
  - name: snow-flow
    dag:
      tasks:
        - name: echo
          template: echo-pre-action
        - name: create-sn-cr
          depends: echo
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: createcr
          arguments:
            parameters:
            - name: TOKEN
              value: cf-api-key-aperture
            - name: CF_RUNTIME
              value: gitops
            - name: SN_INSTANCE
              value: "https://dev201662.service-now.com"
            - name: SN_AUTH
              value: "sn-auth"
            - name: LOG_LEVEL
              value: "debug"
            - name: CR_DATA
              value: >-
                {"short_description": "{{ workflow.parameters.APP_NAME }} deployment",
                "description": "Change for build {{workflow.uid}}.\nThis change was created by the Codefresh GitOps promotion flow",
                "justification": "My app is awesome! Please deploy ASAP",
                "cmdb_ci":"tomcat", "assignment_group":"a715cd759f2002002920bde8132e7018"
                }
        - name: wait
          template: approve
          depends: create-sn-cr
  # Additional templates
  - name: approve
    suspend: {}
      # duration: "72h"
  - name: echo-pre-action
    script:
      image: alpine
      command:
      - sh
      source: |
        echo "syncing {{ workflow.parameters.APP_NAME }} "
