# DO NOT REMOVE the following attributes:
# annotations.codefresh.io/workflow-origin (identifies type of Workflow Template as Promotion Workflow)
# annotations.version (identifies version of Promotion Workflow used)
# annotations.description (identifies intended use of the Promotion Workflow)

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: service-now-close-failure
  annotations:
    codefresh.io/workflow-origin: promotion
    codefresh.io/promotion-stage: post-action
    version: 0.0.1
    description: 'promotion workflow template'

spec:
  serviceAccountName: promotion-template # cf-default-promotion-workflows-sa
  entrypoint: main
  arguments:
    parameters:
    - name: APP_NAME
    - name: CR_SYSID
      value: ""
  templates:
  - name: main
    inputs:
      parameters:
      - name: APP_NAME
      - name: CR_SYSID
    dag:
      tasks:
        - name: close-sn-cr
          templateRef:
            name: argo-hub.servicenow.1.3.0
            template: closecr
          arguments:
            parameters:
            - name: SN_INSTANCE
              value: "https://dev240253.service-now.com/"
            - name: SN_AUTH
              value: "sn-auth"
            - name: CR_DATA
              value: '{"work_notes":"this is a message for the work notes"}'
            - name: CR_SYSID
              value: '{{ inputs.parameters.CR_SYSID }}'
            - name: LOG_LEVEL
              value: info
            - name: CR_CLOSE_CODE
              value: "unsuccessful"
            - name: CR_CLOSE_NOTES
              value: "App {{ workflow.parameters.APP_NAME }} installation failed  so we close the Change Request with error."
