gitops-runtime:
  argo-cd:
    acrController:
      enabled: true
    eventReporter:
      env:
        - name: USE_GRPC
          value: 'false'
      replicas: 4
    server:
      replicas: 2
      resources:
        requests:
          cpu: '0.3'
          memory: 400Mi
  garage-workflows-artifact-storage:
    enabled: true
  global:
    codefresh:
      accountId: 641dfab29939b208915c0d4e
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-public
        enabled: false
      isConfigurationRuntime: true
      name: demoprod
  installer:
    skipValidation: false
