gitops-runtime:
  argo-cd:
    acrController:
      enabled: true
    eventReporter:
      env:
        - name: USE_GRPC
          value: 'false'
      replicas: 4
    server:
      replicas: 2
      resources:
        requests:
          cpu: '0.3'
          memory: 400Mi
  garage-workflows-artifact-storage:
    enabled: true
    persistence:
      # -- Volume that stores artifacts and logs for workflows
      data:
        # -- When empty value empty the default storage class for the cluster will be used
        storageClass: ""
        size: 2Gi
  global:
    codefresh:
      accountId: 641dfab29939b208915c0d4e
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-public
        enabled: false
      isConfigurationRuntime: false
      name: demoprod
  installer:
    skipValidation: false
