apiVersion: v2
appVersion: 0.2.3
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.29.6
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh
    version: 0.29.6
