apiVersion: v2
appVersion: 0.1.72
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.28.1
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh   # /dev
    version: 0.28.1
  - name: argo-rollouts
    repository: https://argoproj.github.io/argo-helm
    version: 2.40.6
