gitops-runtime:
  gitops-operator:
    env: 
      # to be removed when operator is updated to 0.22.0
      PROMOTION_WRAPPER_TEMPLATE: promotion-wrapper-old-workflows
  cf-argocd-extras:
    enabled: true
  argo-cd:
    acrController:
      enabled: true
    eventReporter:
      env:
        - name: USE_GRPC
          value: 'false'
      replicas: 4
    server:
      replicas: 2
      resources:
        requests:
          cpu: '0.3'
          memory: 400Mi
  global:
    codefresh:
      accountId: 641dfab29939b208915c0d4e
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-public
        enabled: false
      isConfigurationRuntime: true
      name: demo
  installer:
    skipValidation: true

  argo-cd:
    configs:
      cm:
        timeout.reconciliation: 2m
    repoServer:
      env:
        - name: ARGOCD_EXEC_TIMEOUT
          value: "5m"

  argo-workflows:
    controller:
      workflowDefaults:
        spec:
          archiveLogs: true
          artifactRepositoryRef:
            configMap: codefresh-workflows-log-store
            key: codefresh-workflows-log-store
    artifactRepositoryRef:
      codefresh-workflows-log-store:
        archiveLogs: true
        codefresh-workflows-log-store:
          s3:
            bucket: 641dfab29939b208915c0d4e
            endpoint: gitops-workflow-logs.codefresh.io
            insecure: false
            keyFormat: 'demo/{{workflow.name}}/{{pod.name}}'
            accessKeySecret:
              name: codefresh-token
              key: token
            secretKeySecret:
              name: codefresh-token
              key: token
