apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-hosted-managed-cluster-gke-codefresh-sa-us-central1-c-temp-dev-cm
  labels:
    app.kubernetes.io/managed-by: codefresh
data: 
  managed-by-runtime: codefresh-hosted
