apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-hosted-managed-cluster-aperture-staging-cm
  labels:
    app.kubernetes.io/managed-by: codefresh
data: 
  managed-by-runtime: codefresh-hosted
