apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: promotion-template
spec:
  applicationSourceSelector:
    matchExpressions:
      - key: codefresh.io/product
        operator: Exists
  priority: 0
  versionSource:
    file: version.yaml
    jsonPath: $.version
  promotion:
    values.yaml:
      jsonPaths:
        - $..image
