apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: demo

spec:
  ingressClassName: haproxy-ingress-public
  rules:
    - host: argocd-tam-demo.rnd.sandbox.codefresh.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: argo-cd-server
                port:
                  number: 8080
