apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aperture-devops
  labels:
    codefresh.io/entity: git-source
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: git-sources
  source:
    repoURL: https://github.com/aperture-sci/DevOps.git
    path: ./apps/.
    targetRevision: main
    directory:
      include: '*'
      exclude: crossplane/*
      recurse: true
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
