apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub
  labels:
    codefresh.io/entity: git-source
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/OctopusSolutionsEngineering/Octopub.git
    path: ./argo
    targetRevision: main
    directory:
      include: '*.yaml'
      exclude: ''
      recurse: true
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
