apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promotion-flow-demo-template
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aperture-sci/promotion-demo-templates.git
    path: .
    targetRevision: main
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
