apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: orders
spec:
  promotionFlows:
    - name: sequential-orders
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[promotion:sequential-orders]'
  promotionTemplateRef: promotion-templates

---

apiVersion: codefresh.io/v1beta1
kind: Product
metadata:
  name: accounts
spec:
  promotionFlows:
    - name: sequential-accounts
      gitTriggerSelectors:
        - key: commitMessage
          operator: In
          values:
            - '[promotion:sequential-accounts]'
  promotionTemplateRef: promotion-templates
