apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: high
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/**/*.yaml,all-runtimes-all-clusters/*.yaml,control-planes/**/*.yaml,control-planes/*.yaml,docker-intg/integration.config.yaml,docker-intg/integration.secret.yaml,high/*.yaml,high/default-git-source.yaml,high/high.yaml,high/prod-east-rollout-reporter.yaml,high/prod-east-rollouts.yaml,high/prod-eu-rollout-reporter.yaml,high/prod-eu-rollouts.yaml,high/prod-west-rollout-reporter.yaml,high/prod-west-rollouts.yaml,runtimes/high/**/*.yaml,runtimes/high/*.yaml}
      recurse: true
    path: resources
    repoURL: >-
      https://github.com/aperture-sci/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
