gitops-runtime:
  global:
    codefresh:
      accountId: 641dfab29939b208915c0d4e
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: crossplane
  argo-cd:
    configs:
      cm:
        application.resourceTrackingMethod: annotation