apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: cf-101
spec:
  priority: 1
  selector:
    product:
      names:
        - cf-101
    targetEnvironment:
      types:
        - PROD
  policy:
    postAction: smoketests
