apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: cf-101-basic-policy
spec:
  priority: -100
  selector:
    product:
      names:
        - cf-101
    targetEnvironment:
      names:
        - dev
        - production
        - qa
        - pro-asia
        - prod-us
        - staging
  policy:
    action: commit
    preAction: pre-action
    postAction: post-action
