apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: memberhsip
spec:
  priority: 1
  selector:
    product:
      names:
        - membership
    targetEnvironment:
      types:
        - PROD
  policy:
    action: commit
