apiVersion: codefresh.io/v1beta1
kind: PromotionPolicy
metadata:
  name: membership-production
spec:
  priority: -200
  selector:
    targetEnvironment:
      types:
        - PROD
  policy:
    action: pr
    postAction: kim-test
