apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argohub-prod
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/codefresh-io/argo-hub.git
      path: .
      targetRevision: codefresh
      directory:
        include: 'workflows/**/*.yaml'
        exclude: '**/images/**/*'
        recurse: true
  destination:
    namespace: demoprod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
