apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: my-octopus-test
  annotations:
    description: "part of testing "
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
    - environment: staging
      dependsOn:
        - dev
      policy:
        action: commit
    - environment: production
      dependsOn:
        - qa
        - staging
      policy:
        action: commit
        postAction: smoketests
