apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: trio-hotfix
  annotations:
    version: 0.0.3
    description: hotfix from Dev to Prod
spec:
  triggerEnvironment: dev
  steps:
    - environment: production
      dependsOn:
        - dev
      policy:
        postAction: smoketests
        action: commit
