apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cf-runtime-app-project
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/aperture-sci/codefresh-runtime-internal-shared-config.git
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
