apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/aperture-sci/DevOps.git
      path: resources
      targetRevision: main
      directory:
        include: '{*.yaml,**/*.yaml}'
        exclude: ''
        recurse: true
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
