apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/aperture-sci/codefresh-runtime-internal-shared-config.git
    targetRevision: HEAD
    path: resources/demo/chart
    helm:
      releaseName: demo
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
