apiVersion: codefresh.io/v1beta1
kind: RestrictedGitSource
metadata:
  name: team-a
spec:
  source:
    repoURL: https://github.com/aperture-sci/DevOps.git
    path: team-a
    targetRevision: HEAD
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destinations:
  - server: '*'
    name: '*'
    namespace: 'team-a'
  - server: '*'
    name: '*'
    namespace: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  sourceRepos:
  - '*'
  sourceNamespace: 'cf-teama'
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
